// Writes supabase/seed-content.sql from src/content/defaults.ts.
// Existing documents are never overwritten (on conflict do nothing), so this
// is safe to run again after the client has started editing.
//   node scripts/seed-content.mjs
import { writeFileSync } from 'node:fs';
import { defaults } from '../src/content/defaults.ts';

const esc = (s) => "'" + s.replace(/'/g, "''") + "'";
const rows = Object.entries(defaults).map(
  ([key, doc]) => `  (${esc(key)}, ${esc(JSON.stringify(doc))}::jsonb, ${esc(JSON.stringify(doc))}::jsonb, now())`
);

const sql = `-- Generated by scripts/seed-content.mjs - do not edit by hand.
insert into public.site_content (key, draft, published, published_at)
values
${rows.join(',\n')}
on conflict (key) do nothing;
`;

writeFileSync(new URL('../supabase/seed-content.sql', import.meta.url), sql);
console.log(`seed-content.sql written (${Object.keys(defaults).length} documents)`);
